const EXTRA_INDIAN_RECIPES = [
    {
        idMeal: 'local_1',
        strMeal: 'Hyderabadi Chicken Biryani',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Hyderabadi_Chicken_Biryani.jpg',
        strCategory: 'Chicken',
        strArea: 'Indian',
        strTags: 'Biryani,Spicy,Main,Dinner,Party',
        strInstructions: '1. Marinate chicken with yogurt, ginger-garlic paste, chili powder, turmeric, and biryani masala for 2 hours.\r\n2. Par-boil basmati rice with whole spices (cardamom, cloves, bay leaf).\r\n3. In a heavy bottom pot, layer the marinated chicken and the par-boiled rice.\r\n4. Add saffron milk, fried onions, and mint leaves on top.\r\n5. Seal the pot with dough or a heavy lid and cook on low heat (dum) for 45 minutes.\r\n6. Serve hot with raita and mirchi ka salan.',
        strIngredient1: 'Chicken', strMeasure1: '1 kg',
        strIngredient2: 'Basmati Rice', strMeasure2: '500g',
        strIngredient3: 'Yogurt', strMeasure3: '200g',
        strIngredient4: 'Fried Onions', strMeasure4: '1 cup',
        strIngredient5: 'Saffron', strMeasure5: '1 pinch',
        strIngredient6: 'Biryani Masala', strMeasure6: '2 tbsp',
        strIngredient7: 'Ghee', strMeasure7: '4 tbsp',
        strIngredient8: 'Mint', strMeasure8: '1 bunch'
    },
    {
        idMeal: 'local_2',
        strMeal: 'Masala Dosa',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Masala_dosa_01.jpg',
        strCategory: 'Breakfast',
        strArea: 'South Indian',
        strTags: 'Breakfast,Vegetarian,Crispy',
        strInstructions: '1. Soak rice and urad dal separately for 6 hours. Grind to a smooth batter and ferment overnight.\r\n2. Boil potatoes and mash them. Sauté mustard seeds, curry leaves, onions, turmeric, and green chilies. Mix with potatoes to make the filling.\r\n3. Heat a flat pan (tawa). Pour a ladle of batter and spread it thin.\r\n4. Drizzle oil/ghee around the edges.\r\n5. When crispy, place a scoop of potato filling in the center and fold.\r\n6. Serve hot with coconut chutney and sambar.',
        strIngredient1: 'Rice', strMeasure1: '3 cups',
        strIngredient2: 'Urad Dal', strMeasure2: '1 cup',
        strIngredient3: 'Potatoes', strMeasure3: '4 medium',
        strIngredient4: 'Onions', strMeasure4: '2 chopped',
        strIngredient5: 'Mustard Seeds', strMeasure5: '1 tsp',
        strIngredient6: 'Curry Leaves', strMeasure6: '10-12',
        strIngredient7: 'Turmeric', strMeasure7: '1/2 tsp'
    },
    {
        idMeal: 'local_3',
        strMeal: 'Idli Sambar',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Idli_Sambar-Noida-UP-SP004.jpg',
        strCategory: 'Breakfast',
        strArea: 'South Indian',
        strTags: 'Breakfast,Healthy,Steamed,Vegetarian',
        strInstructions: '1. Make batter using soaked rice and urad dal (4:1 ratio), ground and fermented.\r\n2. Pour batter into idli molds and steam for 10-12 minutes.\r\n3. For Sambar: Cook toor dal with vegetables (drumstick, carrot, pumpkin).\r\n4. Temper mustard seeds, curry leaves, and dry red chilies. Add onions and tomatoes.\r\n5. Add sambar powder, tamarind pulp, and the cooked dal.\r\n6. Boil for 10 minutes and garnish with coriander. Serve with fluffy idlis.',
        strIngredient1: 'Rice', strMeasure1: '1 kg',
        strIngredient2: 'Toor Dal', strMeasure2: '1 cup',
        strIngredient3: 'Mixed Vegetables', strMeasure3: '2 cups',
        strIngredient4: 'Sambar Powder', strMeasure4: '2 tbsp',
        strIngredient5: 'Tamarind', strMeasure5: '2 tbsp'
    },
    {
        idMeal: 'local_4',
        strMeal: 'Butter Chicken',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Butter_Chicken_with_Naan.JPG',
        strCategory: 'Chicken',
        strArea: 'North Indian',
        strTags: 'Curry,Rich,Dinner',
        strInstructions: '1. Marinate chicken chunks with yogurt, lemon, and spices for 1 hour. Grill or pan-fry until cooked.\r\n2. In a pan, melt butter. Add whole spices and pureed tomatoes. Cook until oil separates.\r\n3. Add cashew paste, cream, sugar, and kasuri methi (dried fenugreek).\r\n4. Add the cooked chicken and simmer for 10 minutes.\r\n5. Finish with fresh cream and butter. Serve with Naan.',
        strIngredient1: 'Chicken', strMeasure1: '500g',
        strIngredient2: 'Butter', strMeasure2: '50g',
        strIngredient3: 'Tomato Puree', strMeasure3: '1.5 cups',
        strIngredient4: 'Cream', strMeasure4: '1/2 cup',
        strIngredient5: 'Cashew nuts', strMeasure5: '2 tbsp',
        strIngredient6: 'Fenugreek', strMeasure6: '1 tsp'
    },
    {
        idMeal: 'local_5',
        strMeal: 'Vegetable Biryani',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Veg-Biryani.jpg',
        strCategory: 'Vegetarian',
        strArea: 'Indian',
        strTags: 'Rice,Vegetarian,Spicy',
        strInstructions: '1. Sauté spices, onions, and mixed vegetables (carrots, peas, beans, cauliflower) in ghee.\r\n2. Add ginger-garlic paste, biryani masala, and yogurt. Cook until veggies are half done.\r\n3. In a pot, layer the vegetable masala and partially cooked basmati rice.\r\n4. Add saffron water, mint, and fried onions.\r\n5. Cover and cook on low heat (dum) for 20 minutes.',
        strIngredient1: 'Basmati Rice', strMeasure1: '2 cups',
        strIngredient2: 'Mixed Vegetables', strMeasure2: '2 cups',
        strIngredient3: 'Yogurt', strMeasure3: '1/2 cup',
        strIngredient4: 'Biryani Masala', strMeasure4: '2 tbsp',
        strIngredient5: 'Paneer', strMeasure5: '100g'
    },
    {
        idMeal: 'local_6',
        strMeal: 'Paneer Butter Masala',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Paneer_Butter_Masala.jpg',
        strCategory: 'Vegetarian',
        strArea: 'Indian',
        strTags: 'Curry,Vegetarian,Dinner',
        strInstructions: '1. Shallow fry paneer cubes and set aside.\r\n2. Prepare a gravy base with onions, tomatoes, cashews, and spices. Blend to a smooth paste.\r\n3. Cook the paste in butter. Add cream, garam masala, and fenugreek leaves.\r\n4. Add paneer cubes and simmer for 5 minutes.\r\n5. Garnish with coriander and cream.',
        strIngredient1: 'Paneer', strMeasure1: '250g',
        strIngredient2: 'Tomato', strMeasure2: '4',
        strIngredient3: 'Cream', strMeasure3: '1/4 cup',
        strIngredient4: 'Butter', strMeasure4: '2 tbsp',
        strIngredient5: 'Cashew nuts', strMeasure5: '10'
    },
    {
        idMeal: 'local_7',
        strMeal: 'Samosa',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Samosa_1.jpg',
        strCategory: 'Starter',
        strArea: 'Indian',
        strTags: 'Snack,Street Food,Vegetarian',
        strInstructions: '1. Prepare dough with flour, ajwain (carom seeds), salt, and oil. Rest for 30 mins.\r\n2. Mash boiled potatoes. Sauté with peas, ginger, cumin, coriander powder, and garam masala.\r\n3. Roll small balls of dough into ovals, cut in half. Form a cone, stuff with filling, and seal edges with water.\r\n4. Deep fry on medium-low heat until golden brown and crispy.\r\n5. Serve with mint chutney and tamarind chutney.',
        strIngredient1: 'Flour', strMeasure1: '2 cups',
        strIngredient2: 'Potatoes', strMeasure2: '4 boiled',
        strIngredient3: 'Peas', strMeasure3: '1/2 cup',
        strIngredient4: 'Ajwain', strMeasure4: '1/2 tsp',
        strIngredient5: 'Oil', strMeasure5: 'For frying'
    },
    {
        idMeal: 'local_8',
        strMeal: 'Gulab Jamun',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Gulab_Jamuns.jpg',
        strCategory: 'Dessert',
        strArea: 'Indian',
        strTags: 'Sweet,Dessert,Festival',
        strInstructions: '1. Mix milk powder, flour, and baking soda. Add warm milk/cream to make a soft dough.\r\n2. Form small smooth balls without cracks.\r\n3. Heat oil/ghee on low. Fry balls slowly until dark golden brown.\r\n4. Make sugar syrup with sugar, water, cardamom, and rose water.\r\n5. Soak the fried balls in warm syrup for at least 2 hours before serving.',
        strIngredient1: 'Milk Powder', strMeasure1: '1 cup',
        strIngredient2: 'Flour', strMeasure2: '1/4 cup',
        strIngredient3: 'Sugar', strMeasure3: '1.5 cups',
        strIngredient4: 'Cardamom', strMeasure4: '4 pods',
        strIngredient5: 'Rose Water', strMeasure5: '1 tsp'
    },
    {
        idMeal: 'local_9',
        strMeal: 'Pav Bhaji',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pav_bhaji_from_Mumbai.JPG',
        strCategory: 'Vegetarian',
        strArea: 'Street Food',
        strTags: 'Spicy,Street Food,Dinner',
        strInstructions: '1. Boil and mash vegetables (potatoes, cauliflower, peas, carrots).\r\n2. Sauté onions, ginger-garlic paste, and capsicum in butter.\r\n3. Add Pav Bhaji masala, chili powder, and tomatoes. Cook until mushy.\r\n4. Mix in mashed veggies and water. Mash everything together on the pan.\r\n5. Add lots of butter and coriander. Toast Pav (buns) with butter.\r\n6. Serve hot with chopped onions and lemon.',
        strIngredient1: 'Potatoes', strMeasure1: '3',
        strIngredient2: 'Cauliflower', strMeasure2: '1 cup',
        strIngredient3: 'Peas', strMeasure3: '1/2 cup',
        strIngredient4: 'Pav Bhaji Masala', strMeasure4: '2 tbsp',
        strIngredient5: 'Butter', strMeasure5: '50g',
        strIngredient6: 'Bun', strMeasure6: '8'
    },
    {
        idMeal: 'local_10',
        strMeal: 'Pani Puri',
        strMealThumb: 'https://commons.wikimedia.org/wiki/Special:FilePath/Panipuri.jpg',
        strCategory: 'Snack',
        strArea: 'Street Food',
        strTags: 'Street Food,Spicy,Vegan',
        strInstructions: '1. Prepare the Pani: Blend coriander, mint, green chilies, ginger, and tamarind. Dilute with water. Add pani puri masala and salt.\r\n2. Prepare the Filling: Mix mashed boiled potatoes with black chickpeas, chili powder, and salt.\r\n3. Use store-bought Puris or fry ready-to-fry pellets.\r\n4. Crack a hole in the Puri, add filling, dip in the spicy water, and eat immediately.',
        strIngredient1: 'Puri', strMeasure1: '20',
        strIngredient2: 'Mint', strMeasure2: '1 cup',
        strIngredient3: 'Coriander', strMeasure3: '1 cup',
        strIngredient4: 'Tamarind', strMeasure4: '1 tbsp',
        strIngredient5: 'Potatoes', strMeasure5: '2 boiled'
    }
];
